version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 1000
